<?php

namespace AppBundle\Repository;


/**
 * ConvergenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvergenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByInvitation($userToken, $isActive){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('u')
            ->from('AppBundle\Entity\User', 'u')
            ->join('u.invitations', 'i')
            ->join('i.convergence', 'c')
            ->where("u.userToken = :userToken")
            ->andWhere("c.is_active = :isActive")
            ->getQuery();
        $query->setParameter('userToken', $userToken);
        $query->setParameter('isActive', $isActive);
        $invitations = $query->getResult();
        return $invitations;
    }
}
