<?php

namespace AppBundle\Repository;

/**
 * ConvergenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvergenceRepository extends \Doctrine\ORM\EntityRepository
{
}
