AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Repository\UserRepository
    oneToMany:
      convergences:
        targetEntity: AppBundle\Entity\Convergence
        mappedBy: creator
      placess:
        targetEntity: AppBundle\Entity\Place
        mappedBy: creator
      locations:
        targetEntity: AppBundle\Entity\UserLocation
        mappedBy: user
      invitations:
        targetEntity: AppBundle\Entity\Invitation
        mappedBy: user
      createdInvitations:
        targetEntity: AppBundle\Entity\Invitation
        mappedBy: creator
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        creationDate:
            type: datetime
            nullable: false
        modificationDate:
            type: datetime
            nullable: true
        firstname:
            type: string
            length: 100
        lastname:
            type: string
            length: 100
        email:
            type: string
            length: 255
        phone:
            type: string
            length: 100
            nullable: true
        image:
            type: string
            length: 255
        userToken:
            type: string
            length: 255


